# Create model using kmeans with 7 clusters
CREATE OR REPLACE MODEL
`lithe-hallway-271806.SupermarketData.CLUSTERS`
OPTIONS(model_type='kmeans', num_clusters=7)
AS (
SELECT
COUNT(DISTINCT BASKET_ID) AS TOTAL_VISIT,
AVG(SPEND) AS SPEND_PER_VISIT,
AVG(SHOP_HOUR) AS SHOP_HOUR_PER_VISIT,
AVG(QUANTITY) AS QUANTITY_PER_VISIT
FROM `lithe-hallway-271806.SupermarketData.SUPERMARKET`
WHERE CUST_CODE IS NOT NULL
GROUP BY CUST_CODE
)

# Group the customers into clusters predicted by the model
SELECT
* EXCEPT(nearest_centroids_distance)
FROM
ML.PREDICT( MODEL `lithe-hallway-271806.SupermarketData.CLUSTERS`,
(
SELECT
COUNT(DISTINCT BASKET_ID) AS TOTAL_VISIT,
AVG(SPEND) AS SPEND_PER_VISIT,
AVG(SHOP_HOUR) AS SHOP_HOUR_PER_VISIT,
AVG(QUANTITY) AS QUANTITY_PER_VISIT
FROM `lithe-hallway-271806.SupermarketData.SUPERMARKET`
WHERE CUST_CODE IS NOT NULL
GROUP BY CUST_CODE
))