SELECT 
    CURRENT_MONTH, 
    NEW_CUST, 
    REPEAT_CUST, 
    REACTIVATED_CUST,
    REPEAT_CUST - LAG(TOTAL, 1) OVER(ORDER BY CURRENT_MONTH) AS CHURN_CUST
FROM
    (SELECT
        CURRENT_MONTH, 
        COUNT(CASE WHEN STATUS = 'NEW' THEN CUST_CODE ELSE NULL END) AS NEW_CUST, 
        COUNT(CASE WHEN STATUS = 'REPEAT' THEN CUST_CODE ELSE NULL END) AS REPEAT_CUST, 
        COUNT(CASE WHEN STATUS = 'REACTIVATED' THEN CUST_CODE ELSE NULL END) AS REACTIVATED_CUST,
        COUNT(CUST_CODE) AS TOTAL
    FROM
        (SELECT 
            PREVIOUS_MONTH, CURRENT_MONTH, CUST_CODE, 
            CASE
                WHEN DATE_DIFF(CURRENT_MONTH, PREVIOUS_MONTH, MONTH) IS NULL THEN 'NEW'
                WHEN DATE_DIFF(CURRENT_MONTH, PREVIOUS_MONTH, MONTH) = 1 THEN 'REPEAT'
                WHEN DATE_DIFF(CURRENT_MONTH, PREVIOUS_MONTH, MONTH) > 1 THEN 'REACTIVATED'
            ELSE NULL END AS STATUS
        FROM
            (SELECT 
                LAG(CURRENT_MONTH, 1)OVER(PARTITION BY CUST_CODE ORDER BY CURRENT_MONTH) AS PREVIOUS_MONTH,
                CURRENT_MONTH,
                CUST_CODE
            FROM
                (SELECT
                    DISTINCT DATE_TRUNC(SHOP_DATE, MONTH)CURRENT_MONTH, 
                    CUST_CODE
                FROM `lithe-hallway-271806.SupermarketData.SUPERMARKET` 
                WHERE 
                    CUST_CODE IS NOT NULL)))
        GROUP BY 
            CURRENT_MONTH)
ORDER BY
    CURRENT_MONTH;